#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/.config/polybar/launch.sh &

$HOME/.fehbg
feh --bg-max --no-fehbg --randomize ~/Pictures/

bspc monitor -d I II III IV V VI VII VIII 
bspc monitor HDMI-1 -d IX X

bspc config border_width         1
bspc config window_gap           1

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
 

# NetworkManager is the most popular way to manage wireless networks on Linux,
# and nm-applet is a desktop environment-independent system tray GUI for it.
# Update: nm-applet replaced by networkmanager_dmenu and pa-applet incorporated
# into the polybar
nm-applet &
pa-applet &
blueman-applet &

# for battery
xfce4-power-manager &
